### ISSUE TITLE
Error: Invalid ACK (0) in DAP response when trying to interface Jtag board with saml21 board through openocd.

### ISSUE THREAD

**Issue by Ravikiran16218** [syncsrc/jtagsploitation#4]
Hello Sir Im facing an isuue when im trying to interface Atmel SamL21 Board with Jtag Board through OpenOcd sever. It is throwing an  "Invalid ACK (0) in DAP response " Error.
please check the below log for complete error details.

`openocd -f interface/ftdi/ngxtech.cfg  -f target/at91samdXX.cfg`
After running the above command  i'm betting the below error logs.

```
Open On-Chip Debugger 0.10.0+dev-00735-g56568b7-dirty (2019-06-10-18:27)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
WARNING!
This file was not tested with real interface, but is assumed to work as this
interface uses the same layout as configs that were verified. Please report your
experience with this file to openocd-devel mailing list, so it could be marked
as working or fixed.
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
none separate
adapter speed: 1500 kHz
cortex_m reset_config sysresetreq
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 1500 kHz
Error: JTAG scan chain interrogation failed: all zeroes
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: at91samd.cpu: IR capture error; saw 0x00 not 0x01
Warn : Bypassing JTAG setup events due to errors
Error: Invalid ACK (0) in DAP response
Error: Invalid ACK (0) in DAP response
Error: Invalid ACK (0) in DAP response
Error: Invalid ACK (0) in DAP response
```
```
-----------------------------------------------------------------------------------
Someone Please help me to solve the above problem.
please find the attached documents below.

**Comment by securelyfitz** [comment]
>Error: JTAG scan chain interrogation failed: all zeroes

The first error is where to start. You are not communicating with the device properly. Either your not hooking the right connections up, or you are not using the right configuration files for your target.

I've never used an ngxtech jtag adapter and haven't dealt with SAMD processors much. You're best bet is to seek support for the jtag adapter, cpu, and openocd.

Once you have openocd up and running properly, if you're trying to get one of the jtag-to-root techniques discussed here working, feel free to open a relevant issue.

**Comment by Ravikiran16218** [comment]
Hello Sir  i was interfacing  with  Atmel Sam5d36Xplained board earlier ,for this board i was able interact with the same JTag adapter. And in the Configuration it is mentioned that config will be able to support for sam5d36 ,samd21 and saml21 board also.I have attached the configuration files below. Please help me where im going wrong  so that i can solve the above issue...

[at91samdXX.txt](https://github.com/syncsrc/jtagsploitation/files/3276116/at91samdXX.txt)
[ngxtech.txt](https://github.com/syncsrc/jtagsploitation/files/3276117/ngxtech.txt)

**Comment by securelyfitz** [comment]
You're going wrong in one of two ways. Either:
- You're using the wrong tools and target. This repository covers some specific techniques using the Adafruit FT232H and Raspberry Pi.
- You're asking for help in the wrong place. A forum for openocd, the ngxtech adapter, or the atsamd would be the place to start if you're trying to get that platform working.
