### ISSUE TITLE
I can't flash the DMA card

### ISSUE THREAD

**Issue by Marmeladov1** [syncsrc/jtagsploitation#5]
After a bad firmware, I can't do anything. I love it
下载程序启动成功 fo : sector 0 took 161 ms Open On-Chip Debugger 0.11.0+dev-00706-g822097a35-dirty (2022-09-29-16:46) Licensed under GNU GPL v2 For bug reports, read http://openocd.org/doc/doxygen/bugs.html Info : only one transport option; autoselect 'jtag' adapter speed: 10000 kHz xc7_program jt agspi_program Info : clock speed 100 00 kHz Info : JTAG tap: xc7.tap tap/device found: 0x13632093 (mfg: 0x049 (Xilinx), part: 0x3632, ver: 0x1) Info : JTAG tap: xc7.tap tap/device found: 0x13632093 (mfg: 0x049 (Xilinx), part: 0x3632, ver: 0x1) Error: xc7.tap: IR capture error; saw 0x07 not 0x01 Warn : Bypassi ng JTAG setup event s due to errors Error: Unknown flash d evice (ID 0x030202) Info : Close the CH347. BIN 文件下载完成. 下载程序关闭成功

**Comment by Marmeladov1** [comment]
下载程序启动成功 Info : sector 0 took 169 Open On-Chip Debugger 0.11.0+dev-00706-g822097a35-dirty (2022-09-29-16:46) Licensed under GNU GPL v2 For bug reports, read http://openocd.org/doc/doxygen/bugs.html Info : only one transport option; autoselect 'jtag' adapter speed: 10000 kHz xc7_program jtagspi_program I nfo : clock speed 10000 kHz Info : J TAG tap: xc7.tap tap/device found: 0x136 32093 (mfg: 0x049 (Xilinx), part: 0x3632, ver: 0x1) Error: IR capture error at bit 6, saw 0x0 1 not 0x...3 Warn : Bypassing JTAG setup events due to errors I n fo : JTAG tap: xc7. tap tap/device found: 0x00010001 (mfg: 0x000 (<inva lid>), part: 0x0010, ver: 0x0) Wa rn : JTAG tap: xc7.tap UNEXPECTED: 0x00010001 (mfg: 0x000 (<invalid>), part: 0x0010, ver: 0x 0) Error: JTAG tap: xc7.tap expected 1 o f 35: 0x03622093 (mfg: 0x049 (Xilinx), part: 0x3622, ver: 0x0) Error: JTAG tap: xc7.tap expected 2 of 35: 0x03620093 (mfg: 0x049 (Xilinx), part: 0x3620, ver: 0x0) Error: JTAG tap: xc7.tap expected 3 of 35: 0x037c4093 (mfg: 0x049 (Xilinx), par t: 0x37c4, ver: 0x0) Error: JTAG tap: xc7.tap expect ed 4 of 35: 0x0362f093 (mfg: 0x049 (Xilinx), part: 0x362f, ver: 0x0) Error: JTAG tap: xc7.tap expected 5 of 35: 0x037c8093 (mfg: 0x049 (Xilinx), part: 0x37c8, ver: 0x0) Error: JTAG tap: xc7.tap expected 6 of 35: 0x037c7093 (mfg: 0x049 (Xilinx), part: 0x37c7, ver: 0x0) Error: JTAG tap: xc7.tap expected 7 of 35: 0x037c3093 (mfg: 0x049 (Xilinx), part: 0x37c3, ver: 0x0) Error: JTAG tap: xc7.tap expected 8 of 35: 0x0362e093 (mfg: 0x049 (Xilinx), part: 0x362e, ver: 0 x0) Error: JTAG tap: xc7.tap expected 9 of 35: 0x037c2093 (mfg: 0x049 (Xilinx), part: 0x37c2, ver: 0x0) Error: JTAG tap: xc7.tap expected 10 of 3: 0x0362d093 (mfg: 0x049 (Xilinx), part: 0x362d, ver: 0x0) Error: JTAG tap: xc7.tap expected 11 of 3: 0x0362c093 (mfg: 0x049 (Xilinx), part: 0x362c, ver: 0x0) Error: JTAG tap: xc7.tap expected 12 of 3: 0x03632093 (mfg: 0x049 (Xilinx), part: 0x3632, ver: 0x0) Error: JTAG tap: xc7.tap expected 1 3 of 3: 0x03631093 (mfg: 0x049 (Xilinx), part: 0x3631, ver: 0x0) Error: JTAG tap: xc7.tap expected 14 of 3: 0x03636093 (mfg: 0x049 (Xilinx), part: 0x3636, ver: 0x0) Error: JTAG tap: xc7.tap expected 15 of 3: 0x03647093 (mfg: 0x049 (Xilinx), part: 0x3647, ver: 0x0) Error: JTAG tap: xc7.tap expected 16 of 3: 0x0364c093 (mfg: 0x049 (Xilinx), part: 0x364c, ver: 0x0) Error: JTAG tap: xc7.tap expected 17 of 3: 0x03651093 (mfg: 0x049 (Xilinx), part: 0x3651, ver: 0x0) Error: JTAG tap: xc7.tap expected 18 of 3: 0x03747093 (mfg: 0x049 (Xilinx), part: 0x3747, ver: 0x0) Error: JTAG tap: xc7.tap expected 19 of 3: 0x03656093 (mfg: 0x049 (Xilinx), part: 0x3656, ver: 0x0) Error: JTAG tap: xc7.tap expected 20 of 3: 0x03752093 (mfg: 0x049 (Xilinx), part: 0x3752, ver: 0x0) Error: JTAG tap: xc7.tap expected 21 of 3: 0x03751093 (mfg: 0x049 (Xilinx), part: 0x37 51, ver: 0x0) Error: JTAG tap: xc7.tap expected 22 of 3: 0x03671093 (mfg: 0x049 (Xilinx), part: 0x3671, ver: 0x0) Error: JTAG tap: xc 7.tap expected 23 of 3: 0x036b3093 (mfg: 0x049 (Xilinx), part: 0x36b3, ver: 0x0) Error: JTAG tap: xc7.tap expected 24 of 3: 0x036b7093 (mfg: 0x049 (Xilinx), part: 0x36b7, ver: 0x0) Error: JTAG tap: xc7.tap expected 25 of 3: 0x036bb093 (mfg: 0x049 (Xilinx), part: 0x36bb, ver: 0x0) Error: JTAG tap: xc7.tap expect ed 26 of 3: 0x036bf093 (mfg: 0x049 (Xilinx), part: 0x36bf, ver: 0x0) Error: JTAG tap: xc7.tap expected 27 of 3: 0x03667093 (mfg: 0x049 (Xilinx), part: 0x3667, ver: 0x0) Error: JTAG tap: xc7.tap expected 28 of 3: 0x03682093 (mfg: 0x049 (Xilinx), part: 0x3682, ver: 0x0) Error: JTAG tap: xc7.tap expected 29 of 3: 0x03687093 (mfg: 0x049 (Xilinx), part: 0x3687, ver: 0x0) Error: JTAG tap: xc7.tap expected 30 of 3: 0x03692093 (mfg: 0x049 (Xilinx), part: 0x3692, ver: 0x0) Error: JTAG tap: xc7.tap expected 31 of 3: 0 x03691093 (mfg: 0x049 (Xilinx), part: 0x3691, ver: 0x0) Error: JTAG tap: xc7.tap expected 32 of 3: 0x03696093 (mfg: 0x049 (Xilinx), part: 0x3696, ver: 0x0) Error: JTAG tap: xc7.tap expected 33 of 3: 0x036d5093 (mfg: 0x049 (Xilinx), part: 0x36d5, ver: 0x0) Error: JTAG tap: xc7.tap expected 34 of 3: 0x036d9093 (mfg: 0x049 (Xilinx), part: 0x36d9, ver: 0x0) Error: JTAG tap: xc7.tap expected 35 of 3: 0x036db093 (mfg: 0x049 (Xilinx), part: 0x36db, ver: 0x0 ) Info : JTAG tap: auto0.tap tap/device found: 0x01010101 (mfg: 0x080 (<invalid>), part: 0x1010, ver: 0x0) Info : TAP auto1.tap does not have valid IDCODE (idcode=0x930053d4) Info : TAP auto2.tap does not have valid IDCODE (idcode=0x498029ea) I nfo : JTAG tap: auto3.tap tap/device found: 0x24c014f5 (mfg: 0x27a (Arkados), part: 0x4c01, ver: 0x2) Info : TAP auto4.tap does not have valid IDCODE (idcode=0xffc4d8c8) Info : TAP auto5.tap does not have valid IDCODE (idcode=0xffe26c64) Info : TAP auto6.tap does not have valid IDCODE (idcode=0xfff13632) Info : JTAG tap: auto7.tap tap/device found: 0xfff89b19 (mfg: 0x58c (Black Sesame Technologies Inc), part: 0xff89, ver: 0xf) Error: Trying to use configured scan chain anyway... Warn : AUTO auto0.tap - use "jtag newtap auto0 tap -irlen 2 -expected-id 0x01010101" Error: auto0.tap: IR capture error; saw 0x0003 not 0x0001 Warn : Bypassing JTAG setup events due to errors Error: Unknown flash device (ID 0x000200) Info : Close the CH347. BIN 文件下载完成. 下载程序关闭成功

**Comment by securelyfitz** [comment]
Not sure how this relates to the materials covered in jtagsploitation. Reopen if you feel otherwise and can help us understand.
